/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as FakeAPIRouteImport } from './routes/FakeAPI'
import { Route as ContextAPIRouteImport } from './routes/ContextAPI'
import { Route as IndexRouteImport } from './routes/index'

const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeAPIRoute = FakeAPIRouteImport.update({
  id: '/FakeAPI',
  path: '/FakeAPI',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextAPIRoute = ContextAPIRouteImport.update({
  id: '/ContextAPI',
  path: '/ContextAPI',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ContextAPI': typeof ContextAPIRoute
  '/FakeAPI': typeof FakeAPIRoute
  '/people': typeof PeopleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ContextAPI': typeof ContextAPIRoute
  '/FakeAPI': typeof FakeAPIRoute
  '/people': typeof PeopleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ContextAPI': typeof ContextAPIRoute
  '/FakeAPI': typeof FakeAPIRoute
  '/people': typeof PeopleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ContextAPI' | '/FakeAPI' | '/people'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ContextAPI' | '/FakeAPI' | '/people'
  id: '__root__' | '/' | '/ContextAPI' | '/FakeAPI' | '/people'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextAPIRoute: typeof ContextAPIRoute
  FakeAPIRoute: typeof FakeAPIRoute
  PeopleRoute: typeof PeopleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FakeAPI': {
      id: '/FakeAPI'
      path: '/FakeAPI'
      fullPath: '/FakeAPI'
      preLoaderRoute: typeof FakeAPIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContextAPI': {
      id: '/ContextAPI'
      path: '/ContextAPI'
      fullPath: '/ContextAPI'
      preLoaderRoute: typeof ContextAPIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextAPIRoute: ContextAPIRoute,
  FakeAPIRoute: FakeAPIRoute,
  PeopleRoute: PeopleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
