/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReactHooksRouteImport } from './routes/ReactHooks'
import { Route as PeopleRouteImport } from './routes/People'
import { Route as AnilistRouteImport } from './routes/Anilist'
import { Route as IndexRouteImport } from './routes/index'

const ReactHooksRoute = ReactHooksRouteImport.update({
  id: '/ReactHooks',
  path: '/ReactHooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/People',
  path: '/People',
  getParentRoute: () => rootRouteImport,
} as any)
const AnilistRoute = AnilistRouteImport.update({
  id: '/Anilist',
  path: '/Anilist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Anilist': typeof AnilistRoute
  '/People': typeof PeopleRoute
  '/ReactHooks': typeof ReactHooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Anilist': typeof AnilistRoute
  '/People': typeof PeopleRoute
  '/ReactHooks': typeof ReactHooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Anilist': typeof AnilistRoute
  '/People': typeof PeopleRoute
  '/ReactHooks': typeof ReactHooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Anilist' | '/People' | '/ReactHooks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Anilist' | '/People' | '/ReactHooks'
  id: '__root__' | '/' | '/Anilist' | '/People' | '/ReactHooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnilistRoute: typeof AnilistRoute
  PeopleRoute: typeof PeopleRoute
  ReactHooksRoute: typeof ReactHooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ReactHooks': {
      id: '/ReactHooks'
      path: '/ReactHooks'
      fullPath: '/ReactHooks'
      preLoaderRoute: typeof ReactHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/People': {
      id: '/People'
      path: '/People'
      fullPath: '/People'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Anilist': {
      id: '/Anilist'
      path: '/Anilist'
      fullPath: '/Anilist'
      preLoaderRoute: typeof AnilistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnilistRoute: AnilistRoute,
  PeopleRoute: PeopleRoute,
  ReactHooksRoute: ReactHooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
